CREATE TABLE IF NOT EXISTS tenants (
  id BIGINT PRIMARY KEY,
  name VARCHAR(255) NOT NULL,
  business_type INT,
  create_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  update_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

ALTER TABLE tenants OWNER TO postgres;
